name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v3

      - name: Deploy to Hugging Face (Bypassing PDF)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          rm -f "User Manual.pdf"
          rm -rf .git

          git init
          git checkout -b main
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Deploy to Hugging Face (PDF Excluded)"

          git push --force https://leoniegasteiner:${HF_TOKEN}@huggingface.co/spaces/leoniegasteiner/Lunar-Regolith-Database main